// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	authapi "lina-core/api/auth"
	authsvc "lina-core/internal/service/auth"
	"lina-core/internal/service/bizctx"
)

type ControllerV1 struct {
	authSvc   *authsvc.Service
	bizCtxSvc *bizctx.Service
}

func NewV1() authapi.IAuthV1 {
	return &ControllerV1{
		authSvc:   authsvc.New(),
		bizCtxSvc: bizctx.New(),
	}
}
