// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysFileUsageDao is the data access object for the table sys_file_usage.
// You can define custom methods on it to extend its functionality as needed.
type sysFileUsageDao struct {
	*internal.SysFileUsageDao
}

var (
	// SysFileUsage is a globally accessible object for table sys_file_usage operations.
	SysFileUsage = sysFileUsageDao{internal.NewSysFileUsageDao()}
)

// Add your custom methods and functionality below.
