// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysUserMessageDao is the data access object for the table sys_user_message.
// You can define custom methods on it to extend its functionality as needed.
type sysUserMessageDao struct {
	*internal.SysUserMessageDao
}

var (
	// SysUserMessage is a globally accessible object for table sys_user_message operations.
	SysUserMessage = sysUserMessageDao{internal.NewSysUserMessageDao()}
)

// Add your custom methods and functionality below.
