// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dept

import (
	"backend/api/dept"
	deptsvc "backend/internal/service/dept"
)

type ControllerV1 struct {
	deptSvc *deptsvc.Service
}

func NewV1() dept.IDeptV1 {
	return &ControllerV1{
		deptSvc: deptsvc.New(),
	}
}
