
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "sqlite::@file(./temp/data/data.db)"
        tables: "sys_user"
        descriptionTag: true
        noModelComment: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
