// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package loginlog

import (
	"lina-core/api/loginlog"
	loginlogsvc "lina-core/internal/service/loginlog"
)

type ControllerV1 struct {
	loginLogSvc *loginlogsvc.Service
}

func NewV1() loginlog.ILoginlogV1 {
	return &ControllerV1{
		loginLogSvc: loginlogsvc.New(),
	}
}
