// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package monitor

import (
	"lina-core/api/monitor"
	"lina-core/internal/service/auth"
	"lina-core/internal/service/servermon"
	"lina-core/internal/service/session"
)

type ControllerV1 struct {
	authSvc      *auth.Service
	serverMonSvc *servermon.Service
}

func NewV1() monitor.IMonitorV1 {
	return &ControllerV1{
		authSvc:      auth.New(),
		serverMonSvc: servermon.New(),
	}
}

// sessionStore returns the session store from auth service.
func (c *ControllerV1) sessionStore() session.Store {
	return c.authSvc.SessionStore()
}
