// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package monitor

import (
	"lina-core/api/monitor"
	"lina-core/internal/service/auth"
	"lina-core/internal/service/servermon"
	"lina-core/internal/service/session"
)

// ControllerV1 系统监控控制器
type ControllerV1 struct {
	authSvc      *auth.Service      // 认证服务
	serverMonSvc *servermon.Service // 服务器监控服务
}

// NewV1 创建系统监控控制器实例
func NewV1() monitor.IMonitorV1 {
	return &ControllerV1{
		authSvc:      auth.New(),
		serverMonSvc: servermon.New(),
	}
}

// sessionStore returns the session store from auth service.
func (c *ControllerV1) sessionStore() session.Store {
	return c.authSvc.SessionStore()
}
