// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package operlog

import (
	"backend/api/operlog"
	operlogsvc "backend/internal/service/operlog"
)

type ControllerV1 struct {
	operLogSvc *operlogsvc.Service
}

func NewV1() operlog.IOperlogV1 {
	return &ControllerV1{
		operLogSvc: operlogsvc.New(),
	}
}
