// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package runtime

import (
	runtimeapi "lina-plugin-demo-runtime/backend/api/runtime"
	runtimesvc "lina-plugin-demo-runtime/backend/service/runtime"
)

// ControllerV1 is the review-only controller for the runtime sample plugin.
type ControllerV1 struct {
	runtimeSvc *runtimesvc.Service // runtimeSvc provides review-only backend example data.
}

// NewV1 creates and returns a new runtime sample controller instance.
func NewV1() runtimeapi.IRuntimeV1 {
	return &ControllerV1{
		runtimeSvc: runtimesvc.New(),
	}
}
