// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	authapi "backend/api/auth"
	authsvc "backend/internal/service/auth"
)

type ControllerV1 struct {
	authSvc *authsvc.Service
}

func NewV1() authapi.IAuthV1 {
	return &ControllerV1{
		authSvc: authsvc.New(),
	}
}
