// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict

import (
	"lina-core/api/dict"
	dictsvc "lina-core/internal/service/dict"
)

type ControllerV1 struct {
	dictSvc *dictsvc.Service
}

func NewV1() dict.IDictV1 {
	return &ControllerV1{
		dictSvc: dictsvc.New(),
	}
}
