// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dynamic

import (
	dynamicapi "lina-plugin-demo-dynamic/backend/api/dynamic"
	dynamicsvc "lina-plugin-demo-dynamic/backend/service/dynamic"
)

// ControllerV1 is the review-only controller for the dynamic sample plugin.
type ControllerV1 struct {
	dynamicSvc *dynamicsvc.Service // dynamicSvc provides review-only backend example data.
}

// NewV1 creates and returns a new dynamic sample controller instance.
func NewV1() dynamicapi.IDynamicV1 {
	return &ControllerV1{
		dynamicSvc: dynamicsvc.New(),
	}
}
