// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	userapi "lina-core/api/user"
	usersvc "lina-core/internal/service/user"
)

type ControllerV1 struct {
	userSvc *usersvc.Service
}

func NewV1() userapi.IUserV1 {
	return &ControllerV1{
		userSvc: usersvc.New(),
	}
}
