// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sysinfo

import (
	"lina-core/api/sysinfo"
	sysinfosvc "lina-core/internal/service/sysinfo"
)

type ControllerV1 struct {
	sysInfoSvc *sysinfosvc.Service
}

func NewV1() sysinfo.ISysinfoV1 {
	return &ControllerV1{
		sysInfoSvc: sysinfosvc.New(),
	}
}
