// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	"lina-core/api/file"
	filesvc "lina-core/internal/service/file"
)

type ControllerV1 struct {
	fileSvc *filesvc.Service
}

func NewV1() file.IFileV1 {
	return &ControllerV1{
		fileSvc: filesvc.New(),
	}
}
